4_semestre/05.Fiap.Web.MVC/05.Fiap.Web.MVC/Models/Bar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _05.Fiap.Web.MVC.Models
{
    public class Bar
    {

        public string Nome { get; set; }
        public string Descricao { get; set; }
        public bool Menores { get; set; }
        public string Cidade { get; set; }


    }
}

4_semestre/05.Fiap.Web.MVC/05.Fiap.Web.MVC/Controllers/BarController.cs
using _05.Fiap.Web.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _05.Fiap.Web.MVC.Controllers
{
    public class BarController : Controller
    {

        private static List<Bar> _bares = new List<Bar>();

        // GET: Bar
        [HttpGet]
        public ActionResult Cadastrar()
        {
            List<string> cidades = new List<string>();
            cidades.Add("São Paulo");
            cidades.Add("Rio de Janeiro");
            cidades.Add("Curitiba");
            // enviar para a pagina a lista de cidades para o select
            ViewBag.listaCidades = new SelectList(cidades);
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Bar bar)
        {
            _bares.Add(bar);
            // TempData mantem por 2 requests!!!
            TempData["msg"] = "Bar cadastrado com sucesso!";
            return RedirectToAction("Cadastrar");
        }

        public ActionResult Listar()
        {
            return View(_bares);
        }

    }
}

4_semestre/05.Fiap.Web.MVC/05.Fiap.Web.MVC/Views/Bar/Cadastrar.cshtml
@model _05.Fiap.Web.MVC.Models.Bar

@{
    ViewBag.Title = "Cadastrar Bar";
}


<h2>Cadastrar Bar</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm())
{

    <div class="form-group">
        @Html.LabelFor(bar => bar.Nome)
        @Html.TextBoxFor(bar => bar.Nome)
    </div>

    <div class="form-group">
        @Html.LabelFor(bar => bar.Descricao)
        @Html.TextAreaFor(bar => bar.Descricao)
    </div>

    <div class="form-group">
        @Html.CheckBoxFor(bar => bar.Menores)
        @Html.LabelFor(bar => bar.Menores)
    </div>

    <div class="form-group">
        @Html.LabelFor(bar => bar.Cidade)
        @Html.DropDownListFor(bar => bar.Cidade, ViewBag.listaCidades as SelectList)
    </div>

    <input type="submit" class="btn btn-primary" value="Cadastrar" />

}

4_semestre/05.Fiap.Web.MVC/05.Fiap.Web.MVC/Views/Bar/Listar.cshtml
@model List<_05.Fiap.Web.MVC.Models.Bar>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<table class="table table-striped table-hover">

    <thead>
        <tr>
            <th>Nome</th>
            <th>Descricao</th>
            <th>Menores</th>
            <th>Cidade</th>
        </tr>
    </thead>

    @foreach (var bar in Model)
    {
        <tr>
            <td>@bar.Nome</td>
            <td>@bar.Descricao</td>
            <td>@(bar.Menores?"Aceita menores" : "Proibido menores")</td>
            <td>@bar.Cidade</td>
        </tr>
    }

</table>

4_semestre/05.Fiap.Web.MVC/05.Fiap.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP Bares", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastrar Bar", "Cadastrar", "Bar")</li>
                    <li>@Html.ActionLink("Listar Bares", "Listar", "Bar")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>